name: azblob
description: |
  A trivial Azure Blob Storage client.
  You can get and put Blob on server side dart.
version: 3.0.1
homepage: https://github.com/kkazuo/dart-azblob

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  crypto: ^3.0.3
  http_parser: ^4.0.0
  universal_io: ^2.2.2

dev_dependencies:
  lint: ^2.0.0
  test: ^1.16.8
